-- AlterTable
ALTER TABLE "Facturas" ADD COLUMN     "descuExenta" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "descuGravada" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "descuNoSuj" DOUBLE PRECISION DEFAULT 0;
